### ISSUE TITLE
DNAC Request to Clean Up the Templates

### ISSUE THREAD

**Issue by Reth11** [CiscoDevNet/learning-labs-issues#195] opened 2019-10-08 21:50 UTC
https://developer.cisco.com/learning/modules/dnac-rest-apis/dnac-template-prg/step/1

There are many titles that can be changed or removed, which will make the lab look more professional. Recommend removing anything 'test' or where someone held down the 'f' key.

<img width="305" alt="034" src="https://user-images.githubusercontent.com/50714/66435899-73267f80-e9eb-11e9-89f5-e8a7dbfc2b91.PNG">
<img width="292" alt="035" src="https://user-images.githubusercontent.com/50714/66435901-73267f80-e9eb-11e9-94aa-21a2ed13f164.PNG">
<img width="292" alt="036" src="https://user-images.githubusercontent.com/50714/66435902-73267f80-e9eb-11e9-8a49-f1fe9207c02e.PNG">

**Comment by JoelRiglerIG** [comment] 2019-10-09 19:12
@Reth11 :  This seems like a Sandbox maintenance issue - and not a doc or Learning Labs 'correctness' or 'enhancement' issue. The issue is still valid - but I wonder if there are other issue tracking databases that are more appropriate for Sandbox maintenance.  Nonetheless, I've include this question in a set of issues and questions directed to Tom Davies, whom I'm told manages these Sandboxes.

**Comment by Reth11** [comment] 2019-10-16 13:15
When I say, professional I mean more polished. If a user's first experience is logging into a system and they see a bunch of tests in their environment, I personally wonder why it was cleaned up and did they figure it out. I believe that Cisco has a high bar for reputation and I am wanting the labs and documents to be the best we can do.

**Comment by annegentle** [comment] 2019-10-22 14:41
Also revise the Lab to show how to get to the Template Editor - Tools > Template Editor, with this screenshot.
<img width="224" alt="Screen Shot 2019-10-22 at 9 37 48 AM" src="https://user-images.githubusercontent.com/501981/67297848-124d7b80-f4b0-11e9-9d54-ae6d35e95f53.png">

**Comment by annegentle** [comment] 2019-10-22 14:42
This Sandbox's templates have been cleared so there are not as many "test" templates.

**Comment by jrigler** [comment] 2019-11-27 22:57
_Slice of email exchange with Tom Davies (Oct 10, 2019):_

Question: Is there any active regular ‘sanitation’ or cleanup of the Always On Sandboxes?  One logged ‘issue’ noted that there are number of configuration templates with ‘unprofessional’ names and ‘test’ names. (I saw none that we should be concerned about that were ‘bad words’, etc).  My first reaction was to think that ‘of course’ these are resources that are intended to be shared with the user community so users can add any configuration templates they like.  The issue’s point was relevant however.  Are these systems cleaned up or reset on some schedule?
 
[TD] No sanitisation or reset today, but there should be. It’s a question of time / resources within DevNet to get to it, but it can be backlogged for automation. Thanks for raising!

**Comment by vvaliapa** [comment] 2022-07-20 16:17
Closing this issue since we don't have any test templates currently

**Closed as completed by vvaliapa** 2022-07-20 16:17 UTC
Labels: needs-ll-changes
