### ISSUE TITLE
DNAC Request for URL in Image

### ISSUE THREAD

**Issue by Reth11** [CiscoDevNet/learning-labs-issues#156] opened 2019-10-01 20:00 UTC
### Cisco DNA Center Platform - Network Devices
https://developer.cisco.com/learning/modules/dnac-rest-apis/network_device/step/1

May we please, have an image that contains the URL portion in the browser?

<img width="902" alt="013" src="https://user-images.githubusercontent.com/50714/65995862-e82e0e00-e45b-11e9-9d6a-7e99abe6fb48.PNG">

I know it seems trivial, but having the URL really helps in troubleshooting and the customer experience will be improved for some users.

**Comment by Reth11** [comment] 2019-10-01 21:53
### Execute Commands Across the Network with Cisco DNA Center Platform and Command Runner
https://developer.cisco.com/learning/modules/dnac-rest-apis/dnac-cmd-run/step/1

Recommend to have a URL as part of the picture.
<img width="657" alt="028" src="https://user-images.githubusercontent.com/50714/66003526-f71cbc80-e46b-11e9-8aeb-3768e3635456.PNG">

**Comment by JoelRiglerIG** [comment] 2019-10-08 00:57
Question to reviewers: Should the Learning Labs be specific to a Sandbox or DNA Center?  Or should they be written to be generic.?

**Comment by Reth11** [comment] 2019-10-09 14:13
My opinion is that if we are generating sandboxes for the lab, then the documentation should be specific. When the customer is following along with their own devices and expected to have their own devices then the documentation should be generic.

**Comment by JoelRiglerIG** [comment] 2019-10-09 17:56
@Reth11 ,  My impression is that Cisco is providing Sandboxes for various labs and to allow user/developers to create, test, and learn on their own.  The original question was intended to ask to what degree should or could each Learning Lab class set be specific to a specific Sandbox (e.g.  Release Version,  DNAC components, virtual device components, etc) vs. generalized to a random or generic DNA Center. 

In this case - and probably for most - if / when we use an image or screenshot, I'll temper the display with text that says something like:  "You should see something like the following, depending on the configuration of your specific DNA Center."

**Comment by srshalini** [comment] 2022-09-29 08:07
I have done the necessary steps. Hence closing the issue.

**Closed as completed by srshalini** 2022-09-29 08:07 UTC
Labels: enhancement, question
